### ISSUE TITLE
being idle forever

### ISSUE THREAD

**Issue by iranpak** [caloskao/migrate-specific#2]
hi.
when i run php artisan migrate:specific /path/to/migration it does nothing and goes in an infinite sleep and idle. whats wrong with it?

**Comment by caloskao** [comment]
Hi, can you run `php artisan migrate:specific -vvv /path/to/migration` to print debug info and paste it here?

**Comment by Welfordian** [comment]
I am also having this issue... it's just hanging. Adding the `-vvv` option gives no output. There's no error, it's just hanging forever.

MySQL output is as such... (`SHOW FULL PROCESSLIST;`)

```
+----+--------+------------------+--------+---------+------+----------+-----------------------+
| Id | User   | Host             | db     | Command | Time | State    | Info              |
+----+--------+------------------+--------+---------+------+----------+-----------------------+
| 73 | [****] | 172.18.0.2:40994 | [****] | Sleep   |   85 |          | NULL            |
+----+--------+------------------+--------+---------+------+----------+-----------------------+
```

**Comment by Welfordian** [comment]
The problematic line seems to be `$instance->run(new ArrayInput($args), $output);` at `private function callArtisanBySymfony`.

It seems, however, that running the migration with `php artisan migrate —path=` runs the migration.

**Comment by caloskao** [comment]
@Welfordian This issue may occur when migrating in a production environment, you can try the pre-release version [v2.0.0-beta.2](https://github.com/caloskao/migrate-specific/releases/tag/v2.0.0-beta.2).
