### ISSUE TITLE
Is it possible to set foreign key checks = 0 during migration?

### ISSUE THREAD

**Issue by biocrypto730** [caloskao/migrate-specific#3]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I get an error in laravel like "could not add/drop table, foreign key check fails". In a raw MySQL command, I can get around this by running the command: "set foreign_key_checks=0; {{ add/drop command }}; set foreign_key_checks=1;". This stackoverflow question also describes a PHP/Laravel way to do it using Schemas: https://stackoverflow.com/questions/34298639/laravel-migrations-nice-way-of-disabling-foreign-key-checks

**Describe the solution you'd like**
A simple command like option like --no-foreign-key-checks or just -f 

**Describe alternatives you've considered**
Running the command using hardwired mysql commands in a bash script. Not very applicable when using multiple databases

**Additional context**
This library is awesome, and has really improved since the first version!!!! Thank you for making this. It is a dream and should be included in the next version of laravel.... A while back I tried to make some of the improvements you've made and did not get very far... So congrats!!!

**Comment by caloskao** [comment]
In standard practice, ignoring foreign key checks should be placed in the migration file, but in some cases it does make development work cumbersome. This feature is an effective solution and will be released in the next version.
